/** @type {import('tailwindcss').Config} */
const v = (name) => `rgb(var(--${name}) / <alpha-value>)`;
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['selector', '[data-theme="dark"], .dark'],
  theme: {
    extend: {
      fontFamily: { sans: ['"Inter Variable"', 'Inter', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'] },
      // Every colour is a CSS variable so light and dark share one set of class names (see src/index.css)
      colors: {
        canvas: v('canvas'),
        surface: { DEFAULT: v('surface'), 2: v('surface-2'), 3: v('surface-3'), raised: v('surface-raised') },
        line: { DEFAULT: v('line'), strong: v('line-strong') },
        ink: { DEFAULT: v('ink'), 2: v('ink-2'), 3: v('ink-3') },
        primary: { DEFAULT: v('primary'), hover: v('primary-hover'), soft: v('primary-soft'), ink: v('primary-ink') },
        success: { DEFAULT: v('success'), hover: v('success-hover'), soft: v('success-soft'), ink: v('success-ink') },
        warning: { DEFAULT: v('warning'), soft: v('warning-soft'), ink: v('warning-ink') },
        danger: { DEFAULT: v('danger'), soft: v('danger-soft'), ink: v('danger-ink') },
        inverse: { DEFAULT: v('inverse'), ink: v('on-inverse') },
        overlay: v('overlay'),
      },
      fontSize: { meta: ['12px', '16px'], body: ['14px', '20px'], section: ['17px', '24px'], title: ['28px', '34px'] },
      borderRadius: { DEFAULT: '7px', lg: '10px', xl: '14px' },
      boxShadow: {
        xs: 'var(--shadow-xs)', card: 'var(--shadow-card)', lift: 'var(--shadow-lift)', pop: 'var(--shadow-pop)',
        focus: '0 0 0 3px rgb(var(--primary) / 0.22)',
      },
      transitionTimingFunction: { out: 'cubic-bezier(0.16, 1, 0.3, 1)', spring: 'cubic-bezier(0.34, 1.4, 0.64, 1)' },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-out': { from: { opacity: '1' }, to: { opacity: '0' } },
        'page-in': { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'none' } },
        'rise-in': { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'none' } },
        'pop-in': { from: { opacity: '0', transform: 'translateY(-6px) scale(0.97)' }, to: { opacity: '1', transform: 'none' } },
        'pop-out': { from: { opacity: '1', transform: 'none' }, to: { opacity: '0', transform: 'translateY(-4px) scale(0.98)' } },
        'modal-in': { from: { opacity: '0', transform: 'translateY(12px) scale(0.97)' }, to: { opacity: '1', transform: 'none' } },
        'modal-out': { from: { opacity: '1', transform: 'none' }, to: { opacity: '0', transform: 'translateY(8px) scale(0.98)' } },
        'sheet-in': { from: { transform: 'translateY(100%)' }, to: { transform: 'none' } },
        'sheet-out': { from: { transform: 'none' }, to: { transform: 'translateY(100%)' } },
        'toast-in': { from: { opacity: '0', transform: 'translateX(24px) scale(0.96)' }, to: { opacity: '1', transform: 'none' } },
        'toast-out': { from: { opacity: '1', transform: 'none', maxHeight: '120px' }, to: { opacity: '0', transform: 'translateX(24px) scale(0.96)', maxHeight: '0px', marginTop: '-8px' } },
        'slide-down': { from: { opacity: '0', transform: 'translateY(-100%)' }, to: { opacity: '1', transform: 'none' } },
        grow: { from: { transform: 'scaleX(0)' }, to: { transform: 'scaleX(1)' } },
        'grow-y': { from: { transform: 'scaleY(0)' }, to: { transform: 'scaleY(1)' } },
        shimmer: { from: { backgroundPosition: '200% 0' }, to: { backgroundPosition: '-200% 0' } },
        ping: { '0%': { transform: 'scale(1)', opacity: '0.55' }, '80%,100%': { transform: 'scale(2.4)', opacity: '0' } },
        bounce3: { '0%,80%,100%': { transform: 'translateY(0)', opacity: '0.35' }, '40%': { transform: 'translateY(-3px)', opacity: '1' } },
        'badge-pop': { '0%': { transform: 'scale(0.4)' }, '60%': { transform: 'scale(1.18)' }, '100%': { transform: 'scale(1)' } },
        draw: { to: { strokeDashoffset: '0' } },
        'spin-in': { from: { opacity: '0', transform: 'rotate(-90deg) scale(0.6)' }, to: { opacity: '1', transform: 'none' } },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out backwards', 'fade-out': 'fade-out 0.18s ease-in both',
        page: 'page-in 0.32s cubic-bezier(0.16,1,0.3,1) backwards', rise: 'rise-in 0.36s cubic-bezier(0.16,1,0.3,1) backwards',
        'pop-in': 'pop-in 0.18s cubic-bezier(0.16,1,0.3,1) backwards', 'pop-out': 'pop-out 0.14s ease-in both',
        'modal-in': 'modal-in 0.26s cubic-bezier(0.16,1,0.3,1) backwards', 'modal-out': 'modal-out 0.16s ease-in both',
        'sheet-in': 'sheet-in 0.32s cubic-bezier(0.16,1,0.3,1) backwards', 'sheet-out': 'sheet-out 0.2s ease-in both',
        'toast-in': 'toast-in 0.3s cubic-bezier(0.34,1.4,0.64,1) backwards', 'toast-out': 'toast-out 0.22s ease-in both',
        'slide-down': 'slide-down 0.25s cubic-bezier(0.16,1,0.3,1) backwards',
        grow: 'grow 0.7s cubic-bezier(0.16,1,0.3,1) backwards', 'grow-y': 'grow-y 0.6s cubic-bezier(0.16,1,0.3,1) backwards',
        shimmer: 'shimmer 1.6s linear infinite', ping: 'ping 1.8s cubic-bezier(0,0,0.2,1) infinite',
        'badge-pop': 'badge-pop 0.35s cubic-bezier(0.34,1.4,0.64,1) backwards', 'spin-in': 'spin-in 0.3s cubic-bezier(0.34,1.4,0.64,1) backwards',
      },
    },
  },
  plugins: [],
};
